name: Build ESP
on: [push] # コードを保存（Push）するたびに自動でビルド開始！
jobs:
  build:
    runs-on: macos-latest # Appleの環境でビルドするじょ
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build Tweak
        run: make package
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: KnivesOutESP-deb
          path: packages/*.deb
